// Code generated by Kitex v0.2.0. DO NOT EDIT.

package kstudy

import (
	"context"
	"github.com/ag9920/kstudy/kitex_gen/api"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return kStudyServiceInfo
}

var kStudyServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "KStudy"
	handlerType := (*api.KStudy)(nil)
	methods := map[string]kitex.MethodInfo{
		"Concat": kitex.NewMethodInfo(concatHandler, newKStudyConcatArgs, newKStudyConcatResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.2.0",
		Extra:           extra,
	}
	return svcInfo
}

func concatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.KStudyConcatArgs)
	realResult := result.(*api.KStudyConcatResult)
	success, err := handler.(api.KStudy).Concat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKStudyConcatArgs() interface{} {
	return api.NewKStudyConcatArgs()
}

func newKStudyConcatResult() interface{} {
	return api.NewKStudyConcatResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Concat(ctx context.Context, req *api.Request) (r *api.Response, err error) {
	var _args api.KStudyConcatArgs
	_args.Req = req
	var _result api.KStudyConcatResult
	if err = p.c.Call(ctx, "Concat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
