// Code generated by Kitex v0.2.0. DO NOT EDIT.

package exampleservice

import (
	"context"
	server0 "github.com/ag9920/kstudy/genericmap/kitex_gen/kitex/test/server"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return exampleServiceServiceInfo
}

var exampleServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ExampleService"
	handlerType := (*server0.ExampleService)(nil)
	methods := map[string]kitex.MethodInfo{
		"ExampleMethod": kitex.NewMethodInfo(exampleMethodHandler, newExampleServiceExampleMethodArgs, newExampleServiceExampleMethodResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "server",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.2.0",
		Extra:           extra,
	}
	return svcInfo
}

func exampleMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*server0.ExampleServiceExampleMethodArgs)
	realResult := result.(*server0.ExampleServiceExampleMethodResult)
	success, err := handler.(server0.ExampleService).ExampleMethod(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newExampleServiceExampleMethodArgs() interface{} {
	return server0.NewExampleServiceExampleMethodArgs()
}

func newExampleServiceExampleMethodResult() interface{} {
	return server0.NewExampleServiceExampleMethodResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ExampleMethod(ctx context.Context, req *server0.ExampleReq) (r *server0.ExampleResp, err error) {
	var _args server0.ExampleServiceExampleMethodArgs
	_args.Req = req
	var _result server0.ExampleServiceExampleMethodResult
	if err = p.c.Call(ctx, "ExampleMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
