// Code generated by Kitex v0.2.0. DO NOT EDIT.

package exampleservice

import (
	server0 "github.com/ag9920/kstudy/genericmap/kitex_gen/kitex/test/server"
	"github.com/cloudwego/kitex/server"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler server0.ExampleService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
