// Code generated by Kitex v0.2.0. DO NOT EDIT.
package exampleservice

import (
	server0 "github.com/ag9920/kstudy/genericmap/kitex_gen/kitex/test/server"
	"github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler server0.ExampleService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
